name: champer
description: "Champer – is a brand for pet owners who understand that a true relationship with their Pet is about love and dedication. Our comprehensive and innovative approach to feeding animals offers the highest quality products based on unique solutions and functional recipes that support the health and physical and emotional needs of animals. The additives and mixes used in Champer products have been developed by a group of specialists and experts who conduct daily scientific research activities."
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.1
  fast_immutable_collections: ^9.2.0
  comprehensive_utils: ^0.6.0
  flutter_svg: ^2.0.9
  responsive_framework: ^1.4.0
  social_media_buttons: ^1.0.0
  meta_seo: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ganiser
      fonts:
        - asset: assets/fonts/ganiser-ganiser-400.ttf
    - family: poppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
  assets:
    - assets/images/
    - assets/text_images/